// Generated by gencpp from file darias_intelcamera/maplist.msg
// DO NOT EDIT!


#ifndef DARIAS_INTELCAMERA_MESSAGE_MAPLIST_H
#define DARIAS_INTELCAMERA_MESSAGE_MAPLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace darias_intelcamera
{
template <class ContainerAllocator>
struct maplist_
{
  typedef maplist_<ContainerAllocator> Type;

  maplist_()
    : header()
    , center_x()
    , center_y()
    , center_z()
    , sphere_radius(0.0)  {
    }
  maplist_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , center_x(_alloc)
    , center_y(_alloc)
    , center_z(_alloc)
    , sphere_radius(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _center_x_type;
  _center_x_type center_x;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _center_y_type;
  _center_y_type center_y;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _center_z_type;
  _center_z_type center_z;

   typedef double _sphere_radius_type;
  _sphere_radius_type sphere_radius;





  typedef boost::shared_ptr< ::darias_intelcamera::maplist_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::darias_intelcamera::maplist_<ContainerAllocator> const> ConstPtr;

}; // struct maplist_

typedef ::darias_intelcamera::maplist_<std::allocator<void> > maplist;

typedef boost::shared_ptr< ::darias_intelcamera::maplist > maplistPtr;
typedef boost::shared_ptr< ::darias_intelcamera::maplist const> maplistConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::darias_intelcamera::maplist_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::darias_intelcamera::maplist_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::darias_intelcamera::maplist_<ContainerAllocator1> & lhs, const ::darias_intelcamera::maplist_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.center_x == rhs.center_x &&
    lhs.center_y == rhs.center_y &&
    lhs.center_z == rhs.center_z &&
    lhs.sphere_radius == rhs.sphere_radius;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::darias_intelcamera::maplist_<ContainerAllocator1> & lhs, const ::darias_intelcamera::maplist_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace darias_intelcamera

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::darias_intelcamera::maplist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::darias_intelcamera::maplist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::darias_intelcamera::maplist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::darias_intelcamera::maplist_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::darias_intelcamera::maplist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::darias_intelcamera::maplist_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::darias_intelcamera::maplist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "226df555f0c0d330fad82df3aec4cf97";
  }

  static const char* value(const ::darias_intelcamera::maplist_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x226df555f0c0d330ULL;
  static const uint64_t static_value2 = 0xfad82df3aec4cf97ULL;
};

template<class ContainerAllocator>
struct DataType< ::darias_intelcamera::maplist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "darias_intelcamera/maplist";
  }

  static const char* value(const ::darias_intelcamera::maplist_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::darias_intelcamera::maplist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64[] center_x\n"
"float64[] center_y\n"
"float64[] center_z\n"
"\n"
"float64 sphere_radius\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::darias_intelcamera::maplist_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::darias_intelcamera::maplist_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.center_x);
      stream.next(m.center_y);
      stream.next(m.center_z);
      stream.next(m.sphere_radius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct maplist_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::darias_intelcamera::maplist_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::darias_intelcamera::maplist_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "center_x[]" << std::endl;
    for (size_t i = 0; i < v.center_x.size(); ++i)
    {
      s << indent << "  center_x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.center_x[i]);
    }
    s << indent << "center_y[]" << std::endl;
    for (size_t i = 0; i < v.center_y.size(); ++i)
    {
      s << indent << "  center_y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.center_y[i]);
    }
    s << indent << "center_z[]" << std::endl;
    for (size_t i = 0; i < v.center_z.size(); ++i)
    {
      s << indent << "  center_z[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.center_z[i]);
    }
    s << indent << "sphere_radius: ";
    Printer<double>::stream(s, indent + "  ", v.sphere_radius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DARIAS_INTELCAMERA_MESSAGE_MAPLIST_H
